#!/bin/bash

# Devs:
# Nikita kolushov <cod3r@programmer.net>
#
# Log-BackUping Utility is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# You can get a copy of the license at www.gnu.org/licenses
#
source /usr/bin/lbckp_/conf/bckp_fold.conf
export WHITE='\033[1;97m'
export CYAN='\033[1;96m'
export BLUE='\033[1;94m'
export GREEN='\033[1;92m'
export RED='\033[1;91m'
export RESETCOLOR='\033[1;00m'
export numDayDel=${2:-$numDayDel}
date_hms=$(date +'%Y-%m-%d-%h-%m-%s')
export HOME_PATH='/usr/bin/lbckp_'
export LOGS_PATH='/usr/bin/lbckp_/logs'
LOGS="${LOGS_PATH}/${1}_${date_hms}.log"

#access check(root only)
function check_root {

    if [ $(id -u) -ne 0 ]; then
		echo -e -e "\n$GREEN[$RED!$GREEN] $RED You aren't admin use sudo or root!$RESETCOLOR\n" >&2
		exit 1
	fi

}

function dosmth {

  check_root
  ${HOME_PATH}/scripts/${1} | tee ${LOGS}; $0

}

function dell {

  check_root
  ${HOME_PATH}/scripts/${1} ${numDayDel}| tee ${LOGS}; $0 

}

case "$1" in
    help)less $HOME_PATH/$1.txt; $0;
    ;;
    start|clean|strtcnf|shedule|stata|rlist|rstrt|rstat|rclnn)dosmth $1
    ;;
    delld|rdell)dell $1
    ;;
    *)

#Main features menu
echo -e "\n\n
$BLUE             ──= Log-BackUping Utility =──

        $CYAN$""$WHITE""lbckp $CYAN{$WHITE""help$CYAN|$WHITE""start$CYAN|$WHITE""clean$CYAN|$WHITE""stata$CYAN|$WHITE""...$CYAN""}
    
       $CYAN help$BLUE ─────$WHITE Show instructions
       $CYAN start$BLUE ────$WHITE Start backuping directories  
       $CYAN clean$BLUE ────$WHITE Сlean directories [$RED""Del all files$RESETCOLOR]
       $CYAN stata$BLUE ────$WHITE Show statistic
       $CYAN delld$BLUE ────$WHITE $RED""Deleting old archives$WHITE [+180 days]

	  $BLUE ----[ Configuration features ]----
       $CYAN strtcnf$BLUE ──$WHITE Start parameter configuration
       $CYAN shedule$BLUE ──$WHITE Setup backuping in cron scheduler

     $BLUE         ----[ Remote features ]----
       $CYAN rlist$BLUE ────$WHITE Remote hosts list
       $CYAN rstrt$BLUE ────$WHITE Start backuping remote hosts
       $CYAN rstat$BLUE ────$WHITE Show remote hosts statistic
       $CYAN rclnn$BLUE ────$WHITE Сlean remote directories [$RED""Del all files$RESETCOLOR]
       $CYAN rdell$BLUE ────$WHITE $RED""Deleting old remote archives$WHITE [+180 days]
$RESETCOLOR

" >&2
exit 1
;;
esac

echo -e $RESETCOLOR
exit 0
